_BASE_: "Base-Pretrain-Polygon_ch.yaml"
MODEL:
  NUMBER_OF_CHANNEL: [192, 384, 768]
  ##Need to change
  WEIGHTS: "swin_tiny_patch4_window7_224_22k.pth"
  #need to change the weight location
  #WEIGHTS: "detectron2://ImageNetPretrained/torchvision/R-50.pkl"
  #RESNETS:
  #  DEPTH: 50
  TRANSFORMER:
    NUM_FEATURE_LEVELS: 4
    ENC_LAYERS: 6
    DEC_LAYERS: 6
    DIM_FEEDFORWARD: 1024
    HIDDEN_DIM: 256
    DROPOUT: 0.01
    NHEADS: 8
    NUM_QUERIES: 100
    ENC_N_POINTS: 4
    DEC_N_POINTS: 4
SOLVER:
  IMS_PER_BATCH: 1
  BASE_LR: 2e-5
  LR_BACKBONE: 2e-6
  WARMUP_ITERS: 0
  STEPS: (3000000,3500000)
  MAX_ITER: 4000000
  CHECKPOINT_PERIOD: 10000
TEST:
  EVAL_PERIOD: 10000
OUTPUT_DIR: "output/TESTR/pretrain/TESTR_SWINT_Polygon_only_synth+chRects"
